music.setVolume(90)
music.setTempo(174)
music.playTone(277, music.beat(BeatFraction.Half))
music.playTone(233, music.beat(BeatFraction.Half))
music.playTone(277, music.beat(BeatFraction.Whole))
music.playTone(277, music.beat(BeatFraction.Half))
music.playTone(277, music.beat(BeatFraction.Half))
music.playTone(311, music.beat(BeatFraction.Half))
music.playTone(277, music.beat(BeatFraction.Half))
music.playTone(233, music.beat(BeatFraction.Whole))
music.playTone(233, music.beat(BeatFraction.Half))
music.playTone(277, music.beat(BeatFraction.Half))
music.playTone(233, music.beat(BeatFraction.Whole))
music.playTone(233, music.beat(BeatFraction.Half))
music.playTone(277, music.beat(BeatFraction.Half))
music.playTone(233, music.beat(BeatFraction.Whole))
music.playTone(233, music.beat(BeatFraction.Half))
music.playTone(277, music.beat(BeatFraction.Whole))
music.playTone(277, music.beat(BeatFraction.Sixteenth))
music.rest(music.beat(BeatFraction.Whole))
music.playTone(277, music.beat(BeatFraction.Whole))
music.playTone(277, music.beat(BeatFraction.Sixteenth))
music.rest(music.beat(BeatFraction.Whole))
music.playTone(277, music.beat(BeatFraction.Whole))
music.playTone(277, music.beat(BeatFraction.Sixteenth))
music.rest(music.beat(BeatFraction.Double))
music.playTone(277, music.beat(BeatFraction.Whole))
music.playTone(277, music.beat(BeatFraction.Half))
music.playTone(277, music.beat(BeatFraction.Half))
music.playTone(311, music.beat(BeatFraction.Half))
music.playTone(277, music.beat(BeatFraction.Half))
music.playTone(262, music.beat(BeatFraction.Whole))
music.playTone(262, music.beat(BeatFraction.Half))
music.playTone(277, music.beat(BeatFraction.Half))
music.playTone(262, music.beat(BeatFraction.Whole))
music.playTone(262, music.beat(BeatFraction.Half))
music.playTone(277, music.beat(BeatFraction.Half))
music.playTone(262, music.beat(BeatFraction.Whole))
music.playTone(262, music.beat(BeatFraction.Half))
music.playTone(277, music.beat(BeatFraction.Whole))
music.playTone(277, music.beat(BeatFraction.Sixteenth))
music.rest(music.beat(BeatFraction.Whole))
music.playTone(277, music.beat(BeatFraction.Whole))
music.playTone(277, music.beat(BeatFraction.Sixteenth))
music.rest(music.beat(BeatFraction.Whole))
music.playTone(277, music.beat(BeatFraction.Whole))
music.playTone(277, music.beat(BeatFraction.Sixteenth))
